apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: ap-southeast-1

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
      roleName: AmazonEKS_EBS_CSI_DriverRole

vpc:
  id: "vpc-0733f1f987418c813" # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16" # (optional, must match CIDR used by the given VPC)
  securityGroup: "sg-09e5c93f78126c8c5"
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      ap-southeast-1a:
        id: "subnet-0ac7434d43478c68d"
        cidr: "192.168.64.0/18" # (optional, must match CIDR used by the given subnet)

      ap-southeast-1b:
        id: "subnet-01bc2e845bc3967ab"
        cidr: "192.168.128.0/18" # (optional, must match CIDR used by the given subnet)

      ap-southeast-1c:
        id: "subnet-0eea2dd6ef8938e0e"
        cidr: "192.168.192.0/18" # (optional, must match CIDR used by the given subnet)

managedNodeGroups:
  - name: cluster-1-ng-1
    instanceType: t2.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 3
