---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-2
  region: ap-southeast-1

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: true
  clusterEndpoints:
    publicAccess: true
    privateAccess: false

nodeGroups:
  - name: ng-1
    # instanceType: t2.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
