apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: heartbeat
spec:
  type: heartbeat
  version: 8.2.0
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
  config:
    heartbeat.monitors:
      - type: tcp
        schedule: "@every 5s"
        hosts: ["quickstart-es-http.default.svc:9200"]
      - type: tcp
        schedule: "@every 5s"
        hosts:
          - quickstart-kb-http.default.svc:5601
          - fastapi.default.svc:80
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
